[package]
name = "otel"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
axum = { workspace = true, features = ["json"] }
opentelemetry = "0.30.0"
sdk-http.workspace = true
serde_json.workspace = true
tracing.workspace = true
wasi.workspace = true

sdk-otel = { workspace = true, features = ["guest-export", "metrics", "tracing"] }
